### ISSUE TITLE
Screen throws NullReferenceException

### ISSUE THREAD

**Issue by SourceHollandaise** [picoe/Eto#412] opened 2015-12-03 21:58 UTC
EtoForms.Screen throws NullReferenceException

**Comment by cwensley** [comment] 2015-12-03 22:00
Got a repro?  I'm not sure how you are getting the screen.. are you using Window.Screen, Screen.PrimaryScreen/Screens, etc?  I will also need to know what platform(s) this happens on.

**Comment by SourceHollandaise** [comment] 2015-12-03 22:05
Hi!

I'm using the EtoFoms.Window.Screen class. I try to set the size for the MainForm. I'm using this in WinForms.

public MainViewTemplate() : base(typeof(IStorable), null)
        {
            try
            {
                //Screen throws Exception (without stacktrace (I'm using your nuget packages)
               // <package id="Eto.Forms" version="2.0.7" targetFramework="net40" />
                this.Size = (Size)Screen.WorkingArea.Size; 
            }
            catch (Exception ex)
            {
               
            }

            this.WindowState = WindowState.Maximized;
            this.Minimizable = true;
            this.Maximizable = true;

            CreateMainContent();

            CreateMenu();
        }

**Comment by cwensley** [comment] 2015-12-03 22:06
Are you sure you're not getting the NRE from your call to `Screen.WorkingArea`?  Screen will be null until the form is actually shown..

**Comment by cwensley** [comment] 2015-12-03 22:08
... since there's no way to know what screen the form will be shown on, as that is assigned by the OS on multi-monitor setups.

**Comment by SourceHollandaise** [comment] 2015-12-03 22:09
if(Screen != null)
                {

                }

Screen = 'Screen' threw an exception of type 'System.NullReferenceException'

**Comment by SourceHollandaise** [comment] 2015-12-03 22:10
Single monitor setup.

**Comment by cwensley** [comment] 2015-12-03 22:11
Ok great, thanks for checking.  I'll look into it. 

Also, sorry if I wasn't clear - Screen can be null before the form is shown regardless of multi or single monitor.  You can either handle the `Form.Shown` event and use it there, or use `Eto.Forms.Screen.PrimaryScreen`

**Comment by SourceHollandaise** [comment] 2015-12-03 22:14
Ok. I will try this. Look at my solution based on your Framework. Maybe my goal is clearer. I still use Eto. It's great.

https://github.com/SourceHollandaise/Trigger.Smart

**Comment by cwensley** [comment] 2015-12-03 23:34
Hm, I can't really reproduce this issue.  Could you paste a complete stack trace of the error?  Thanks!

**Comment by SourceHollandaise** [comment] 2015-12-03 23:36
Ok, tomorrow. In Austria it is after midnight... I need some sleep now.

**Comment by cwensley** [comment] 2015-12-06 06:15
Just noticed that you're using Eto.Forms 2.0.7, could you give 2.1.0 a try first?  there have been many changes since 2.0.7 that could have fixed this issue.

**Comment by SourceHollandaise** [comment] 2015-12-06 11:10
OK. I will try it. Thanks.

**Comment by cwensley** [comment] 2015-12-27 07:45
Closing this issue as I cannot reproduce it.  If you can provide a repro with the latest develop branch please follow up and we can re-open the issue.

**Closed by cwensley** 2015-12-27 07:45 UTC
