### ISSUE TITLE
(WPF) : WindowStyle.None leaves border and small titlebar 

### ISSUE THREAD

**Issue by rafntor** [picoe/Eto#2125] opened 2022-01-26 15:45 UTC
## Expected Behavior - Gtk looks fine :
![image](https://user-images.githubusercontent.com/44544090/151195470-e5c07f49-ff61-41f5-b655-e744a525aa42.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/44544090/151195588-b11208a2-b2b3-49ed-bc09-a869e3346320.png)

## Code that Demonstrates the Problem
https://github.com/rafntor/EtoDemoApp/blob/windowstyle/EtoDemoApp/EtoDemoApp/MainForm.cs

Not sure if this is a bug but would be preferable if 'None' was really without borders on all platforms

**Comment by cwensley** [comment] 2022-01-26 16:43
Thanks for submitting the issue.  Yes, WPF has a border even when you tell it not to.  I didn't think WinForms had this issue however, maybe it's new.

If you set `myForm.Resizable = false` then the border goes away.

**Comment by rafntor** [comment] 2022-01-26 16:50
Thanks!
Confirming it is OK when resizable=false (should I close it or do you want to improve it to work even without this fix?)
Also confirming I was wrong to include Winforms, double-checked and no such issue there, my bad.

**Comment by cwensley** [comment] 2022-01-26 16:52
I do want to improve this, and actually there was another issue tracking this now that I remember.  I'll close this one as dupe of #1928

**Closed as completed by cwensley** 2022-01-26 16:52 UTC
Labels: bug
