### ISSUE TITLE
Wpf - some little things

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#959] opened 2018-01-20 11:27 UTC
Would it be possible to add these 4 changes to eto.wpf?

```
Eto.Wpf\Forms\ApplicationHandler.cs
public void OnMainFormChanged()
{
    // Tom, we need this, when first form is a splash-screen and mainform is only loading second
	System.Windows.Application.Current.MainWindow =Widget.MainForm.ToNative ();
}


Eto.Wpf\Forms\Controls\GridHandler.cs
protected void RestoreColumnFocus()
{
	// Tom, need try-catch, crash, if last item of grid was removed
	try
	{
		Control.CurrentColumn = null;
		if (Control.Columns.Count > 0)
			Control.CurrentCell = new swc.DataGridCellInfo(Control.SelectedItem, CurrentColumn ?? Control.CurrentColumn ?? Control.Columns[0]);
		CurrentColumn = null;
	}
	catch (Exception  ex)
	{
	}
}

Eto.Wpf\Forms\TableLayoutHandler.cs
public override void UpdatePreferredSize()
{
	base.UpdatePreferredSize();
	for (int y = 0; y < Control.RowDefinitions.Count; y++)
	{
		for (int x = 0; x < Control.ColumnDefinitions.Count; x++)
		{
			var child = controls[x, y];
			var childControl = child.GetWpfFrameworkElement();
			if (childControl != null)
			{
				childControl.ParentMinimumSize = sw.Size.Empty;
			}
		}
	}
	
	// Tom: performance!!!
	// much faster without this line, when resizing a form with tables to fullscreen or back
        // didn't notice any negative effects, if this is missing
	//if (Widget.Loaded)
	//	Control.UpdateLayout();

	SetChildrenSizes();
}


Eto.Wpf\Forms\WpfFrameworkElement.cs
public virtual bool HasFocus
{
	get {
		// Tom, sometimes crash here, add try-catch
		try
		{
			return Control.IsKeyboardFocusWithin;
		}
		catch (Exception ex)
		{
			return false;
		}
	}
}
		
```

**Comment by cwensley** [comment] 2018-01-20 18:49
Also, since you already have code, submitting a PR for each change would be recommended (a single PR with all changes would have to go through more hoops before being accepted).  For example, the first change would probably be able to be merged immediately.

**Comment by cwensley** [comment] 2018-02-01 18:39
Hey @TomQv,

I've added the first fix in.  For the others, please file separate issues with more information.  I won't be able to put those fixes in without the actual exception info and stack trace, or in the case of the slow update some sort of example or steps to reproduce it.

Much appreciated!

**Closed by cwensley** 2018-02-01 18:39 UTC
