### ISSUE TITLE
Xamarin Forms 3.0

### ISSUE THREAD

**Issue by rconde01** [picoe/Eto#807] opened 2017-05-19 15:20 UTC
https://blog.xamarin.com/glimpse-future-xamarin-forms-3-0/

Is there still a future for Eto?

**Comment by TomQv** [comment] 2017-05-19 21:38
very interresting...

**Comment by cwensley** [comment] 2017-05-19 21:45
It is very interesting!  Great to hear they're finally getting around to desktop.  I'm sure it'll still take 1-2 years for it to become a viable option (bugs worked out, full features aka data grid, etc).  In the meantime many people need this today so Eto.Forms works great.

I don't see Eto.Forms going away any time soon with many people depending on it.  Even then we could wrap Xamarin.Forms so it provides a transition between the two.

**Comment by cra0zy** [comment] 2017-05-20 00:49
Xamarin.Forms are horrible, plus they do stuff very differently compared to Xwt and Eto.Forms when it comes to handling backends.

**Comment by Jazzeroki** [comment] 2017-05-20 01:55
Xamarin forms isn't a solution for everything. But for all the business apps I've built with it it's amazing. I don't see eto being replaced though. If a control doesn't exist on every platform then forms doesn't have it and that's caused me problems a number of times.  Eto doesn't seem to limit itself that way.  The 3.0 release of forms though is bringing stuff that platform had been in desperate need of for a long time.  It's nice to see xamarin forms nearing a good maturity.

**Comment by TomQv** [comment] 2017-05-20 07:11
I also like Xamarin.Forms and use it alot. 
The problem is, its very tempting to use and rely on it, but later you run into problems because its still "work-in-progress" so there is lot of things still not right.
For example for our last app we waited almost half a year to get some litle bugs in Xamarin.Forms.UWP fixed, before we could finally release.
Its good that they go for desktop now, but it will take long.
But its the same for Eto, where finding bugs and waiting for fixes also takes very much time.

**Comment by cra0zy** [comment] 2017-05-20 11:35
I hate Xamarin.Forms because I know how to do better UI using just native Android or UWP. On the other hand with Eto.Forms there aren't many things that I need to modify, it mostly has everything.

Also when it comes to bugs just fix them yourself and submit a PR, both projects are open source.

**Comment by cwensley** [comment] 2017-06-09 08:03
Closing this as it isn't really relevant.  Eto will continue on.  Thanks for the inquiry!

**Closed by cwensley** 2017-06-09 08:03 UTC
