### ISSUE TITLE
Drag&Drop?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#706] opened 2017-02-09 07:48 UTC
How about basic drag&drop - functionallity in controls?

**Comment by SlowLogicBoy** [comment] 2017-02-09 07:54
https://github.com/picoe/Eto/issues/320 there is already an issue for that :)
also a pull request https://github.com/picoe/Eto/pull/437 which is inactive quite some time :/

**Comment by cwensley** [comment] 2017-02-15 17:26
Thanks for the report!  The more I hear about this the higher priority I will give it.  It is looking more and more like it should be (much) higher on my list.

**Comment by cwensley** [comment] 2017-02-15 17:26
Closing as duplicate of original issue.

**Closed by cwensley** 2017-02-15 17:26 UTC
Labels: duplicate

**Comment by cra0zy** [comment] 2017-02-15 17:48
> like it should be (much) higher on my list.

From my perspective Drag & Drop is the only major disadvantage Eto has.

**Comment by TomQv** [comment] 2017-02-15 17:52
Same for us, its a killer-feature.
But I knew it would come :-)
