### ISSUE TITLE
Uncertain how to pass through keyhandler events to custom themed control

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1419] opened 2019-05-29 16:28 UTC
There is a modified version of Rob's Eto.Veldrid example at this location

https://github.com/philstopford/Eto.Veldrid

In principle, it should be possible to navigate the control with WASD keys, but they don't seem to get passed through to the handler. I'm not sure why.

## Expected Behavior

WASD should move around the viewport when the control has focus (the mouse is over the control, or has been clicked in the control)

## Actual Behavior

Key handlers are not fired.

## Steps to Reproduce the Problem

Code is at https://github.com/philstopford/Eto.Veldrid
Build and run.
Placing a breakpoint in the keyhandler method (https://github.com/philstopford/Eto.Veldrid/blob/master/src/Eto.VeldridSurface/VeldridDriver.cs), the handler is never called.

## Specifications

  - Version: head
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by cwensley** [comment] 2019-05-29 16:36
Hey @philstopford, great project!

It's because the control is actually a win32 control and doesn't receive any WPF keyboard/mouse events.  You should use [Eto.Wpf.Forms.WindowsFormsHostHandler](https://github.com/picoe/Eto/blob/develop/src/Eto.Wpf/Forms/WindowsFormsHostHandler.cs) as the base handler for the control for WPF, which maps all of the win32/winforms events for the control to Eto.

In poking around, it appears you're using a 'base' themed handler, so you won't be able to use that in order to use the above.

Hope this helps!

**Comment by philstopford** [comment] 2019-05-29 17:44
Curious - the mouse events are being captured, so I just wanted to confirm.

**Comment by ItEndsWithTens** [comment] 2019-05-29 17:44
Thanks for the advice, @cwensley! I wrote the Eto.Veldrid stuff for [my current project](https://github.com/ItEndsWithTens/Arbatel), but it doesn't depend on key events from the VeldridSurface control, so I never noticed anything was wrong there. It's my first custom Eto control, so I expected problems, but hadn't yet run into this one. Lack of experience, and in turn confidence, is a big reason (though hardly the only one) why I didn't write Eto.Veldrid as a library proper, only an example project.

It's been a hot minute since I decided to write that win32-based WpfVeldridHost thing, but as I recall the motivation (beyond generally trying to avoid WinForms if it wasn't necessary) was poor resize performance. In Phil's [etoViewport](https://github.com/philstopford/etoViewport), for example, the WPF test project shows the same issue; its GLSurface class uses the WinFormsHostHandler in WPF, but resizing the test GUI window is sluggish, to say the least.

If I'm remembering correctly, it happened in Eto.Veldrid even when using Vulkan or Direct3D instead of OpenGL, so I can't just blame it on OpenTK's GLControl; is it to be expected that WinForms-in-WPF shows a performance impact on resize?

**Comment by ItEndsWithTens** [comment] 2019-05-31 12:35
My mistake! I must have gotten mixed up somewhere, because I'm just sitting down to try this and I'm not having performance issues on resize with Vulkan or D3D. Flickering, yes, with the control blinking out as I resize the window, but the WindowsFormsHostHandler overall seems promising. I'll keep banging away at it and see if I can get something respectable put together soon.

**Comment by ItEndsWithTens** [comment] 2019-06-02 10:47
Okay, I've been fighting with this for a couple days and have made progress (no more HwndHost or themed base handler), but I'm still not where we need to be. I wonder if I could pester @cwensley to offer some thoughts? I don't want to be a pain, but could use some guidance.

Ignoring Phil's fork for the moment (nothing personal ;) ), I've pushed a few commits to a branch of my original Eto.Veldrid:

https://github.com/ItEndsWithTens/Eto.Veldrid/tree/remove_hwndhost

Among the changes is a pair of test menu items, one to toggle the box's rotation, the other to change its direction. Those commands can also be fired by clicking the control or tapping the C key, respectively. The menu options work in WinForms and WPF equally well (except for my data binding, which doesn't want to go both ways on either platform), but in WinForms the click works to toggle the animation, while the C key does nothing. In WPF it's opposite, with the key toggle working and the click doing nothing.

I realize that my WPF handler for VeldridSurface uses a bare System.Windows.Forms.Integration.WindowsFormsHost as a member variable, instead of the handler itself being based on Eto.Wpf.Forms.WindowsFormsHostHandler. I know that means the various WinForms events aren't wrapped the way Eto's host handler does it, and I've been trying to account for that, without much luck.

For Metal, Vulkan, and Direct3D, all I need to embed Veldrid is a native handle, and to get one of those in WPF I could just use the aforementioned WinForms hosted handler. The problem is OpenGL. The only way I know of to support it is to use a GLSurface, from etoViewport/Eto.OpenTK. Hence my notion of basing VeldridSurface on the Panel class, since it sometimes needs to contain a single child control, the GLSurface instance. That means, as far as I can tell, that I can't just use a WindowsFormsHostHandler for WPF, since GLSurface is already an Eto control, and when using the OpenGL backend I want that GLSurface to be the Content of the VeldridSurface.

As many hours as I've struggled with this, despite glimmers of hope here and there, I ultimately run into the same thing everywhere: either I get key events or mouse events, but never both. I've tried making a separate "RenderTarget" custom class implemented as a WindowsFormsHostHandler in WPF, but despite its underlying WinForms control producing key and mouse events alike (confirmed by overriding the OnMouseDown, etc. methods and setting breakpoints), they never all manage to bubble up to the VeldridSurface that contains the RenderTarget as its Content. I haven't pushed any commits with said RenderTarget class in them, only because the code is as ineffective as what I've already uploaded.

And even if I sorted out WPF, that still wouldn't explain why the WinForms key toggle fails.

Essentially I've gotten as far as my pea brain can get me, and the wild goose chase I've been on has run me a bit ragged. Does it sound like I'm just overlooking anything obvious?

**Comment by ItEndsWithTens** [comment] 2019-06-03 21:25
My previous comment referred to commit ItEndsWithTens/Eto.Veldrid@e4b0ec6, but I changed my mind about that RenderTarget class I mentioned when I realized I do, in fact, have slightly better luck with it. See ItEndsWithTens/Eto.Veldrid@7d729f8 for the latest changes.

Quick note first: although Veldrid allows live backend switching, implementing that is rather involved, and is something I haven't gotten around to. To test different graphics APIs, I just use [line 242 in VeldridSurface.cs](https://github.com/ItEndsWithTens/Eto.Veldrid/blob/7d729f885f435c8c68ea92dde7fd3093aeabc75b/src/Eto.VeldridSurface/VeldridSurface.cs#L242) as a convenient place for quick tests. Just add
```
backend = GraphicsBackend.OpenGL;
```
or Direct3D11, or Vulkan, whatever's appropriate for testing.

On to my current problem: the new "RenderTarget" class is a WindowsFormsHostHandler in WPF, but an ordinary control in WinForms. In WinForms, key and mouse events seem to bubble up just fine no matter whether I use Vulkan, D3D, or OpenGL.

In WPF, pressing C changes the rotation direction as expected, but a temporary override of RenderTarget's OnKeyDown method shows the key event isn't happening there, so it's bubbling up to VeldridSurface some other way. The MouseDown event is another interesting thing, as a breakpoint there does get hit on a mouse click. Unfortunately that event doesn't rise to VeldridSurface, even though the RenderTarget is the Content of that surface.

Am I implementing WindowsFormsHostHandler wrong? It's so close I can taste it, but I can't manage to get it all the way working.

**Comment by cwensley** [comment] 2019-06-03 21:50
Hey @ItEndsWithTens, thanks for the update.  I haven't had time to look into this yet, but I don't think the problem is insurmountable.  Probably something like changing the property of the wpf control to allow keyboard focus is what is missing there, I'm not sure.  I'll try to get some time to look into this but I am currently extremely busy with some deadline stuff that is most certainly making my hair fall out. (;

**Comment by ItEndsWithTens** [comment] 2019-06-03 21:54
Oh absolutely! I don't mean to sound pushy with the walls of text, I just felt it was important to get it all documented sooner rather than later. Get the thoughts out fully before I forget everything.

Godspeed with those deadlines, and my condolences; my hair's falling out without that pressure. :D

**Comment by cwensley** [comment] 2019-06-29 07:09
Hey @ItEndsWithTens, I'm finally looking into this and am trying to run the Eto.Veldrid.Wpf application on your remove_hwndhost branch.  I'm getting the following exception:

```
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateVertexShader(IntPtr shaderBytecodeRef, PointerSize bytecodeLength, ClassLinkage classLinkageRef, VertexShader vertexShaderOut)
   at SharpDX.Direct3D11.VertexShader..ctor(Device device, Byte[] shaderBytecode, ClassLinkage linkage)
   at Veldrid.D3D11.D3D11Shader..ctor(Device device, ShaderDescription description)
   at Veldrid.D3D11.D3D11ResourceFactory.CreateShaderCore(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription description)
   at Veldrid.SPIRV.ResourceFactoryExtensions.CreateFromSpirv(ResourceFactory factory, ShaderDescription vertexShaderDescription, ShaderDescription fragmentShaderDescription, CrossCompileOptions options)
   at PlaceholderName.VeldridDriver.CreateResources() in Z:\Projects\Eto.Veldrid\src\Eto.VeldridSurface\VeldridDriver.cs:line 247
   at PlaceholderName.VeldridDriver.SetUpVeldrid() in Z:\Projects\Eto.Veldrid\src\Eto.VeldridSurface\VeldridDriver.cs:line 155
   at PlaceholderName.MainForm.SetUpVeldrid() in Z:\Projects\Eto.Veldrid\src\Eto.VeldridSurface\MainForm.cs:line 63
   at PlaceholderName.MainForm.set_FormReady(Boolean value) in Z:\Projects\Eto.Veldrid\src\Eto.VeldridSurface\MainForm.cs:line 33
   at PlaceholderName.MainForm.<.ctor>b__10_0(Object sender, EventArgs e) in Z:\Projects\Eto.Veldrid\src\Eto.VeldridSurface\MainForm.cs:line 41
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.Control.OnShown(EventArgs e)
   at Eto.Forms.Control.Callback.OnShown(Control widget, EventArgs e)
   at Eto.Wpf.Forms.WpfWindow`3.<AttachEvent>b__27_8()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Eto.Wpf.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at PlaceholderName.MainClass.Main(String[] args) in Z:\Projects\Eto.Veldrid\src\gui\Eto.Veldrid.Wpf\Program.cs:line 166
```

Not too sure what to do with that one. 

Also, just in looking into the code it appears it's because you're using two levels of (unnecessary?) abstraction.  First, you have the `VeldridSurface` eto control, then _also_ `RenderTarget`, which is a child of VeldridSurface, but only created within each platform.

What I'd suggest is to get rid of RenderTarget completely and make the `VeldridSurfaceHandler`  based off of `WindowsFormsHostHandler` instead.  This should (hopefully?) make everything work as you expect.

Hope this helps!

If I can figure out the above exception I might try to experiment with this myself, but alas it's not something I'm familiar with and it doesn't seem obvious what is wrong.

**Comment by ItEndsWithTens** [comment] 2019-06-29 15:47
Sorry about that crash, I think that might be from your device not supporting D3D11, or at least not the minimum feature level Veldrid requires. I do so wish error messages like "the parameter is incorrect" would go the way of the Dodo. I believe I ran into this once on one of my older systems; Veldrid's testing for D3D11 support only checks [whether it's running on Windows](https://github.com/mellinoe/veldrid/blob/f467b4631769389e5f342db9174ab27387af0bb4/src/Veldrid/GraphicsDevice.cs#L839), and not whether a device can be successfully created.

That means the only remaining Veldrid backend your system likely supports is OpenGL. A simple, brute force way to test would be to add something to the blank [line 242 in VeldridSurface.cs](https://github.com/ItEndsWithTens/Eto.Veldrid/blob/7d729f885f435c8c68ea92dde7fd3093aeabc75b/src/Eto.VeldridSurface/VeldridSurface.cs#L242):
```
backend = GraphicsBackend.OpenGL;
```

The WPF project should run, and you can see [my comment in Eto.Veldrid.Wpf/Program.cs](https://github.com/ItEndsWithTens/Eto.Veldrid/blob/c48ce54007f05eeff3640d81d08fa4db83b34d8c/src/gui/Eto.Veldrid.Wpf/Program.cs#L51) for a description of the strange behavior.

As far as the abstraction, I only introduced the extra layer with RenderTarget in an attempt to solve the problem, and I don't believe I can make WindowsFormsHostHandler the base for VeldridSurface, because of what I mentioned earlier:

> The problem is OpenGL. The only way I know of to support it is to use a GLSurface, from etoViewport/Eto.OpenTK. Hence my notion of basing VeldridSurface on the Panel class, since it sometimes needs to contain a single child control, the GLSurface instance. That means, as far as I can tell, that I can't just use a WindowsFormsHostHandler for WPF, since GLSurface is already an Eto control, and when using the OpenGL backend I want that GLSurface to be the Content of the VeldridSurface.

I'd love to make everything simpler, if it were possible. If that somehow involves eliminating my use of Eto.OpenTK's GLSurface, and re-implementing OpenTK support myself, I'm not against it in principle, but I don't think I have the expertise to do so. OpenGL is, as I understand it, a many-headed beast, with a variety of per-platform gotchas. So far I've been going through GLSurface just because it seems to have successfully accounted for them, and I didn't want to reinvent the wheel if I didn't need to.

---

Worth noting is that I see similar event bubbling oddities in Eto.OpenTK:
- Comment out [line 341 in TestViewport.cs](https://github.com/picoe/Eto.OpenTK/blob/1944fef7450d37be150ec6514aca0ebd79ccbd41/TestEtoOpenTK/TestViewport.cs#L341). This should ensure that key and mouse events are never marked as handled, leaving them to bubble up to their parent controls.
- In the TestViewport project's MainForm class, override OnKeyDown and OnMouseDown, setting a breakpoint in each method.
- Run the TestEtoOpenTK.Wpf GUI project, and click one of the viewports. Nothing happens; the debugger doesn't break on MainForm.OnMouseDown's breakpoint. Now press a key, and it does break. Somehow the mouse works properly, letting you drag the grid around, but the event (despite never being explicitly marked Handled) doesn't rise to the form containing the GLSurface.

I feel like what's happening in Eto.OpenTK's test projects is related to what I'm having in Eto.Veldrid, but I don't know Eto or WPF/WinForms deeply enough to trace where things are going pear-shaped. I know this is a rather involved problem to dump in your lap, but I'm dead in the water, and I don't know who else to consult about this sort of thing.

**Comment by ItEndsWithTens** [comment] 2019-07-14 07:48
With apologies to @cwensley for taking a month and a half to discover this, the issue I'm running into here has apparently jack squat to do with Veldrid, and is purely related to my (mis)understanding of custom controls based on WindowsFormsHostHandler. I've opened a new issue, with a clean test project involving none of the complexity of Eto.Veldrid. I still need help to grasp what I'm doing wrong, but issue #1446 should be more comprehensible, and hopefully makes it easier to determine what needs to happen.

**Comment by philstopford** [comment] 2019-07-26 23:03
Close this one in favor of https://github.com/picoe/Eto/issues/1446?

**Comment by ItEndsWithTens** [comment] 2019-07-26 23:11
I'd say so, yes. I think if that one can get sorted out, it'll be a hop skip and a jump to get this taken care of.

**Closed as completed** 2019-07-26 23:18 UTC
