### ISSUE TITLE
Controls are resized after adding them to PixelLayout (using Gtk3)

### ISSUE THREAD

**Issue by borjafdezgauna** [picoe/Eto#1887] opened 2021-02-02 11:51 UTC
## Expected Behavior
I would have expected controls to keep their sizes after being added to a PixelLayout.

## Actual Behavior
Unlike using Wpf or Mac64 implementations, when I add a control to a PixelLayout using Gtk, the control is resized with a new size (usually 1,1).

## Steps to Reproduce the Problem

  1. Create a pixel layout
  2. Add a control to it using Add()
  3. Check the size of the control after that

## Code that Demonstrates the Problem

```
            PixelLayout pixelLayout = new PixelLayout();
            pixelLayout.Size = new Size(windowSizeInPixelsX, windowSizeInPixelsY);
            Panel panel = new Panel() {Size = new Size(pixelLayout.Width / 2, pixelLayout.Height / 2)};
            pixelLayout.Add(panel,50, 50);
```

## Specifications

  - Version: 2.5.10
  - Platform(s): Gtk3
  - Operating System(s): Windows 10, Ubuntu 20.04 TLS
  
I have had a look at the PixelLayout handler for Gtk and I suspect this is a known issue (there is a comment saying that the minimum size is used instead of the natural size), but haven't found any issue so I thought I'd better report it just in case :)

**Comment by cwensley** [comment] 2021-02-02 16:50
Hey @borjafdezgauna,

Thanks for reporting the issue and providing a code sample to demonstrate the problem.  There is another known issue (#1752) that might be related to this one, but it'll need some digging.

**Comment by cwensley** [comment] 2022-04-24 19:25
I can't seem to reproduce this with this code:

```
	public class TestForm : Form
	{
		public TestForm()
		{
			PixelLayout pixelLayout = new PixelLayout();
			pixelLayout.Size = new Size(200, 200);
			Panel panel = new Panel() { Size = new Size(pixelLayout.Width / 2, pixelLayout.Height / 2), BackgroundColor = Colors.Blue };
			pixelLayout.Add(panel, 50, 50);
			Content = pixelLayout;
		}
	}
```

Perhaps you're doing something different?

I also fixed another issue relating to this with #2196, but with or without that change the above still works for me. 

Could you test with the latest code to see if it's still happening for you?

**Comment by borjafdezgauna** [comment] 2022-04-25 09:20
I have tested the code above on Ubuntu 20, and can confirm that panel shows properly. I am quite sure I actually ran that same code when I created the issue, but hey... I could be wrong

Thanks anyway, Curtis!!

**Comment by cwensley** [comment] 2022-04-25 15:32
@borjafdezgauna thanks for the quick response and testing that out.  I'll close the issue but if you happen to see it again let me know.

**Closed as completed by cwensley** 2022-04-25 15:32 UTC
Labels: needs repro
