### ISSUE TITLE
GridColumn - Indication of sort order

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1180] opened 2018-08-18 14:47 UTC
would be good to have a HeaderImage-Property with GridColumn.
Could be used for a small bitmap indicating the sort-order.

**Comment by msasso69** [comment] 2018-08-18 17:56
I agree it would be good, but I think this is a duplicate of #202 :)

**Comment by cwensley** [comment] 2018-08-30 03:46
I think you mean #283.  Yes, this is a duplicate.  Thanks for reporting the issue!

**Closed by cwensley** 2018-08-30 03:46 UTC
