### ISSUE TITLE
XamMac projects don't run

### ISSUE THREAD

**Issue by observer1** [picoe/Eto#1065] opened 2018-03-22 03:23 UTC
In version 2.4 new xammac projects created with the wizard don't work
At build time this error ocurs:

Projects/Test/Test/Test.XamMac/Assets.xcassets/AppIcon.appiconset/AppIcon-128@2x.png: Error: File not found: /Projects/Test/Test/Test.XamMac/Assets.xcassets/AppIcon.appiconset/AppIcon-128@2x.png (Test.XamMac)

This is because the files are named this way:
AppIcon-128%402x.png

renaming the files remove the errors but then this warning appears trying to debug:

Projects/Prueba/Prueba/Prueba.XamMac/MMP: Warning MM2006: Native library 'libSystem.B.Dylib' was referenced but could not be found. (MM2006) (Prueba.XamMac)

VS shows a message box saying "The application has not been built" and debug doesn't start
Running the application from terminal shows the application starting but it never starts.

Building with msbuild on terminal doesn't generate the warning but the project still doesn't start

**Comment by cwensley** [comment] 2018-03-22 22:09
Thanks for reporting the issue!  The app assets issue is a dupe of #1042.

The warnings for Xamarin.Mac are normal, and are a compile-time warning (MMP is used to compile the .app bundle).

The message of "The application has not been built" is usually because you have deleted the .app bundle manually after compiling.

**Comment by observer1** [comment] 2018-03-23 00:53
I created another project to test, app can be run from finder but vs still shows the messagebox I didn't delete any files in this test

**Comment by nast90210** [comment] 2018-03-28 08:58
I found out how to fix this. Its seem to be working, if in XamMac property Build->Output->Output path set full path to output app file, something like "App.XamMac/bin/Debug/".
I don't understand why it fix problem, but it works.

**Comment by cwensley** [comment] 2018-09-22 06:06
Hm, I'm not running into any of these issues (anymore).  I believe the updates for VS for Mac (I tested 7.6.5) have resolved most if not all of these.  Can you guys give it a try with the latest?

**Comment by cwensley** [comment] 2018-09-27 17:34
I've verified this is no longer an issue.  If you're still having issues with the latest bits, let me know and/or open a new issue.  

Thanks for the feedback everyone!

**Closed by cwensley** 2018-09-27 17:34 UTC
