### ISSUE TITLE
Select Gtk 3 if both Gtk 2 and 3 are installed on Windows, Gtk 2 crashes on OpenFileDialog

### ISSUE THREAD

**Issue by davidscherf** [picoe/Eto#2183] opened 2022-04-09 02:49 UTC
Select Gtk 3 if both Gtk 2 and 3 are installed on Windows
Gtk 2 will crash on OpenFileDialog

## Expected Behavior
Use GTK 3 and have a working OpenFileDialog

## Actual Behavior
Uses GTK 2 and crashes when using OpenFileDialog

Faulting application name: App.exe, version: 1.0.0.0, time stamp: 0x6216d2c0
Faulting module name: libglib-2.0-0.dll, version: 2.66.4.0, time stamp: 0x00000000
Exception code: 0x80000003
Fault offset: 0x00000000000417ba
Faulting process ID: 0x5448
Faulting application start time: 0x01d84bb9c7d6facc
Faulting application path: D:\Somepath\App.exe
Faulting module path: C:\Program Files\GTK2-Runtime Win64\bin\libglib-2.0-0.dll
Report ID: afc3cc7a-e3d2-4a4e-983a-6dbec7f0e02b
Faulting package full name: 
Faulting package-relative application ID: 

## Steps to Reproduce the Problem

  1.  Install on Windows the Gtk runtime for both 2 and 3 from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases
  2.  Make an Eto forms app the uses OpenFileDialog
  3.  Run the code that uses OpenFileDialog

## Code that Demonstrates the Problem

```
            var filters = new System.Collections.ObjectModel.Collection<FileFilter>();
            var dialog = new OpenFileDialog();
            dialog.Filters.Add(new FileFilter("Jpeg", ".jpg"));
            dialog.Filters.Add(new FileFilter("PNG", ".png"));
            if (dialog.ShowDialog(this) == DialogResult.Ok) //Uncapturable crash here on GTK 2
            {

            }
```

## Specifications

  - Version: ETO Forms 2.6.1, GtkSharp 3.24.24.34, GTK 2: 2.24.33, GTK 3: 3.24.31
  - Platform(s): GTK
  - Operating System(s): Windows 10

**Comment by cwensley** [comment] 2022-04-11 02:14
I'm not sure what the problem is?  Currently using Platform.Detect will use Gtk (using gtksharp and Gtk+3), then Gtk3 (for the old gtk-sharp packages on most distros), then Gtk2.

See here for the detection logic: https://github.com/cwensley/Eto/blob/develop/src/Eto/Platform.cs#L414-L420

The only reason it'd use Gtk2 over Gtk3 is if loading Gtk3 fails.

**Comment by cwensley** [comment] 2023-03-17 07:17
Closing as Eto's Gtk 2 is no longer.

**Closed as completed by cwensley** 2023-03-17 07:17 UTC
