### ISSUE TITLE
VS2015 crashes

### ISSUE THREAD

**Issue by ghost** [picoe/Eto#579] opened 2016-10-13 10:26 UTC
VS2015 crashes and restarts after every build with the latest version of the plugin, v2.3.0.12.

**Comment by cwensley** [comment] 2016-10-13 11:21
Thanks for the report, but do you have a bit more information on what your definition contains or steps to reproduce?

This does not happen for me.

Thanks!
Curtis.

**Comment by tomascw** [comment] 2016-10-14 00:08
The project I use requires Full .NET. The definitions I've tried were:
- Full .NET, all-in-one projects with xaml.
- Full. NET, separate projects with xaml.

Other than that I tried removing Mac references. Since I didn't have Xamarin installed at the time.

**Comment by tomascw** [comment] 2016-10-14 03:14
It crashes when ending the application in debug time to time or I've now just gotten a "internal diagnostics hub exception" error.

**Comment by cwensley** [comment] 2016-10-14 09:19
Hey @tomascw, thanks for the info.  I'll see if I can poke VS enough to replicate the issue.  Do you have the latest VS 2015 update installed?

**Comment by tomascw** [comment] 2016-10-15 05:17
I'm assuming so. I'm on 14.0.25431.01 Update 3

**Comment by cwensley** [comment] 2016-10-24 18:15
Hey @tomascw , I still can't repro this, and I've tried it on various machines.   One thing that might be causing an issue is other plugins, perhaps ReSharper or other stuff that integrates with the code editor.  If you can try disabling all 3rd party addins it might help narrow down which one may be causing your issue.

Once we can figure out how to repro it should hopefully be an easy enough fix.

**Comment by tomascw** [comment] 2016-10-26 03:23
I'll see what I can do.

**Comment by TripleWhy** [comment] 2016-12-22 11:24
I do have this (or a similar) issue on my two machines, both Windows 10. I use Visual Studio 2015 Community Edition and got this before (manually) installing any other plugins than eto. For me VS crashes when I try to use the Preview/Designer. When I create any project with preview mode and run/debug (and maybe edit) it a few times, VS eventually crashes. In some cases it will even crash every time it tries to load the project.

Also some debug module seems rather unhappy about the existence of eto since i used to get some nasty error popup very time I tried debugging, but I can't reproduce it now.

I can use eto just fine when I don't use previews.

**Comment by cwensley** [comment] 2016-12-22 19:02
@TripleWhy thanks for the feedback on this!  I've investigated a bit more and it might have something to do with unloading the AppDomain for the preview.  I've not been able to crash VS yet, but I've managed to get it to hang for 10-20 seconds while the appdomain tries to unload.

**Comment by Kizari** [comment] 2017-01-24 12:45
Having the same issue on Windows 10 with Visual Studio 2015 Enterprise. Also on 14.0.25431.01 Update 3.

Steps I follow to reproduce:
1. Create new Eto.Forms application project
2. Select "Combined Windows & Linux assembly, separate Mac
3. Select Full .NET and Xaml
4. Run the default application in debug mode

This is where results vary, sometimes Visual Studio will crash at this point. Other times a dialog will pop up reading "Internal Diagnostics Hub Exception. See log for more details."

Sometimes this will go smoothly, and the preceding errors won't occur until I stop debugging.

The output from the Diagnostics Hub reads as follows:
Request to web host was unsuccessful: 'An error has occurred.'

**Comment by cwensley** [comment] 2017-01-24 17:20
Hi @Kizari, thanks for the detailed feedback, it helps!

**Comment by pielegacy** [comment] 2017-01-25 00:07
Was seriously considering this for a company project but the crashes were just too much. Couldn't get past a build without it shitting the bed in VS 2015 Update 3. Will definitely consider this in future though as I love how powerful it is in concept but it was a bit much for now

**Comment by tomascw** [comment] 2017-02-11 21:28
I recently got a new computer, and I'm giving Eto another whirl. I didn't get a crash this time around. I'll keep ya' posted.

**Comment by SlowLogicBoy** [comment] 2017-02-13 06:31
Since I don't use designer/preview thing, I don't have these kind of problems, well at least haven had yet. 
When I develop Eto app and want to see changes immediately I use F5 in app to refresh layout, here is an [example](https://gist.github.com/SlowLogicBoy/afcd5e068cb8acc28fd2e5b9dd367479#file-mainform-cs-L25), highlighted line is where I usually add my break point and simply use edit and continue feature.

Hope it helps someone.

**Comment by blahlicus** [comment] 2017-08-25 13:07
Just to let you guys know, I am having a similar issue with the "internal diagnostics hub exception" popping up, VS2015 compiles and runs the project successfully, but there's no debugging and the "internal diagnostics hub exception" message pops up when I press "start debugging" and when I press "stop debugging." VS2015 crashes when I try to close it by pressing the "x" button on the top right corner of VS2015.

The above only happens if I start debugging whilst form preview is active and is shown on VS2015, i.e. if I switch to a different window without form preview on VS2015 before startinng, then it starts without problems.

**Comment by cwensley** [comment] 2018-02-06 06:09
Hopefully fixed with #986.  I'm not getting any hub exceptions in 2017, and it seems fairly stable so far.  We'll see as others use it though!

**Closed by cwensley** 2018-02-06 06:09 UTC
Labels: needs repro
