### ISSUE TITLE
[Feature] System trays...

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#587] opened 2016-10-26 21:41 UTC
...for Windows and Linux and Menu Bar Icon for macOS.

**Comment by cwensley** [comment] 2016-10-26 21:41
Duplicate of #291

**Closed by cwensley** 2016-10-26 21:41 UTC

**Comment by claunia** [comment] 2016-10-26 21:44
@cwensley my fault, apologies

**Comment by cwensley** [comment] 2016-10-26 21:44
No prob, there's a lot to go through.. (;
