### ISSUE TITLE
Multi forms

### ISSUE THREAD

**Issue by dajuric** [picoe/Eto#416] opened 2015-12-08 21:22 UTC
How can I open multiple forms if the Application class does not provide Run method for the ApplicationContext (as in WinForms) ?

**Comment by cwensley** [comment] 2015-12-08 21:26
You use the `Application.Initialized` event, like so:

```
var app = new Application();
app.Initialized += (sender, e) => {
	var form1 = new Form { Title = "Form 1", Size = new Size(200, 200), Location = new Point(100, 100) };
	var form2 = new Form { Title = "Form 2", Size = new Size(200, 200), Location = new Point(300, 100) };

	form1.Show();
	form2.Show();
};

app.Run();
```

If this works for you, please close the issue (;

**Comment by dajuric** [comment] 2015-12-08 21:43
Yes, it helps. Thank you.
But, how can I add forms dynamically ? (e.g. one form is showing the image, the other one represents the progress bar which is closed and opened as needed...) ?

**Comment by cwensley** [comment] 2015-12-09 07:02
That really depends on your logic.. you can create forms whenever you want (not just in the initialize event) and show/hide them programatically..

**Comment by dajuric** [comment] 2015-12-09 12:55
Yes, indeed :). 

The goal is to make a few simple forms (for image viewing, progress bar, etc.) which can be called as extensions:
   Bgr<byte>[,] image = ...
   image.Show("My image"); //create a new window if does not exist, otherwise display the new image
or
   UI.ShowProgress("My progress", 20); 
   UI.ShowProgress("My progress", 40);

The problem is, how can I show these forms in asynchronously matter - so those functions do not block the existing code (as Show() opposed to ShowDialog()) ?

**Comment by cwensley** [comment] 2015-12-13 18:24
I'm not sure what the problem is that you're running into?  The `Form.Show()` method does not block so you can show as many forms at the same time as you wish..

**Comment by dajuric** [comment] 2015-12-14 16:45
Not the Form.Show(), but the Application.Run(). I can not use Form.Show() without prior the call Application.Run() and that function is blocking.

So, how can a user create multiple forms using some extension methods as stated in the previous message ? (I am struggling with Application.Run())

**Comment by cwensley** [comment] 2015-12-14 16:47
Ah, did you check the sample in my [comment above](https://github.com/picoe/Eto/issues/416#issuecomment-163022433)?

You use the `Application.Initialize` event to perform your startup code if it's doing more than just showing a single window.

**Comment by dajuric** [comment] 2015-12-14 16:51
Yes, I did. And it works.

But the problem is, I do not know the number of forms in advance.

**Comment by dajuric** [comment] 2015-12-14 16:55
For me, it would be the easiest if I had only the Show() method (which does not require initialization) which runs as long the main thread runs. E.g. I am performing some calculations, showing the progress or a video. When done, everything closes.

Those windows should be dynamically created and destroyed (async). Is it more clear now ?

**Comment by cwensley** [comment] 2015-12-14 16:58
So what determines the number of forms?  You can apply logic in the `Initialized` event to loop or do whatever you need to create as many (or as little) forms as you want.

Perhaps I'm not getting what you're trying to accomplish here?  The `Run()` method *must* block as otherwise the application will just quit immediately without showing anything.  If you have background threads running they can just do something like `Application.Instance.AsyncInvoke(() => new Form{ Title = "MyForm" /*...*/ }.Show())` to show a form or do any UI logic whenever they need to. 

As for closing the application, if you set `Application.MainForm`, the application will close when that form is closed.  Otherwise you must perform your own logic and call Application.Instance.Quit() when you want to close the application.

**Comment by dajuric** [comment] 2015-12-14 17:16
Thank you.

But maybe a more concrete example:
    
  static void Main()
  {
        for(int i=0; i < 1000; i++)
        {
             //process an i-th image
             UI.ShowProgress("progress1", (float)i/1000); //(create a form if not already shown and set the progress)
        } 
        
        UI.CloseWindows("progress1");

         for(int i=0; i < 1000; i++)
        {
             //take the-ith image
             UI.ShowImage("imageWnd", img); //(create a form if not already shown and set the image)
        } 

        UI.CloseWindow("imageWnd");
         
       //the end - all windows should close
  }

1) How can I do that ?
   1.1) the problems I see: dynamic number of windows (Initialized Event fires once and at that time the number of forms is unknown)
   1.2) in theory I do not need Application.Run() because the "image processing" functions are blocking and forms should be shown as long as those functions run (until the final statement is the app is not reached)
   1.3) I have tried using "Show()" and then use Thread.Sleep(1000) to simulate blocking operation - failed. 
          I have also tried AsyncInvoke - nothing comes up
          And finally, I used the Application.Run() within a task that I waited - again nothing shown
          (finally, I do not know how to tackle the problem).

I apologize for being boring, and thank you for the answers (and hopefully for the answer that will come).

**Comment by cwensley** [comment] 2015-12-14 18:33
Hey no worries at all, it's not always easy to understand what people mean through text alone. However, concrete examples are great, and now I think I understand what you're trying to do.  Thanks!

All UI toolkits use what is called a 'Run Loop', which needs to run to process messages, update window/control state, etc.  Without it, no UI will be shown nor will it be responsive to user input.  Also, UI toolkits are not thread safe, so you must 'invoke' any calls to the UI from that background thread.  Historically, you'd do this by creating a background thread manually and then calling `Application.Instance.Invoke/AsyncInvoke` when you want to update the UI.

Fortunately, this is exactly the type of thing that [async/await](https://msdn.microsoft.com/en-us/library/hh191443.aspx) was created for and will make it easy for you to do this without complicating the code.  I put together a sample that I think is what you're looking for:

https://gist.github.com/cwensley/5eb55557414a71e72693

Hope this helps!
Curtis.

**Comment by dajuric** [comment] 2015-12-14 22:26
Hi,
  many, many thanks!
 Just, if I may, to ask: 

why those tasks must be executed in a separate thread (I see that otherwise does not work, but I do not know why).
Can the execution logic be further simplified as following (MATLAB example):

     fileNames = ...
     for fileName = fileNames
         im = imread(fileName);
         imshow(im); %here I just call show the image, and that figure (window) stays open until another image comes
     end

or in OpenCV (not sure about the syntax):

      cvShowImage(im); //no further initialization required
      cvWaitKey(20); //wait 20ms (or if 0 wait indefinitely) 

Thank you again.

**Comment by cwensley** [comment] 2015-12-14 22:57
The tasks must be executed in a separate thread as the UI is waiting for a run loop to do things such as showing/updating the UI.

When it calls  `await Task.Run(() => ...`, it actually returns from that method, and the UI is given an opportunity to perform UI tasks.  After `Task.Run` is complete, .NET then uses the [SynchronizationContext](https://www.google.ca/search?q=SynchronizationContext) to continue the execution of the method by invoking it on the UI run loop / message queue (the same as if you called `Application.Instance.AsyncInvoke`).

If the async/await is not to your liking, you could instead use `System.Threading.Thread` to start a thread, then wrap all your UI calls in `Application.Instance.AsyncInvoke`.

You could get fancy and start a thread for the UI instead of starting a thread for your logic, though this is not straightforward nor something I'd recommend as a general rule.  I've done this for Eto.Forms' unit tests when you run them externally [here](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/UnitTests/TestUtils.cs#L75).

Either way, you need a separate thread for the UI than you have for your logic.  I would imagine that OpenCV/MATLAB do this for you behind the scenes, assuming they are using any standard UI toolkit.

**Comment by cwensley** [comment] 2015-12-27 07:43
Closing this issue as there's no plans to make Eto.Forms thread safe, since none of the supported UI frameworks are themselves thread safe.  Adding thread safety would add overhead that is better handled by application-specific code when needed.  If you think this should be reconsidered, don't hesitate to let me know, though it is highly unlikely that this will be done.

Thanks for submitting the issue and giving background on your use case.

**Closed by cwensley** 2015-12-27 07:43 UTC

**Comment by dajuric** [comment] 2015-12-28 19:50
I apologize for a long delay. I am not asking you implement thread safe controls, but I merely want to run simple forms as straightforward as possible. I tried the enclosed approach (taken from your unit tests, but I got the following exception: "The calling thread must be STA, because many UI components require this.". I do not know how to avoid this.

The required code is enclosed. I would be grateful if you could take a glance at it and make a suggestion. I really tried several versions.

Thank you.
[TestUtils.cs.txt](https://github.com/picoe/Eto/files/73494/TestUtils.cs.txt)
[Program.cs.txt](https://github.com/picoe/Eto/files/73495/Program.cs.txt)

**Comment by cwensley** [comment] 2015-12-28 20:45
@dajuric, you need to add the [STAThread] attribute to your main() method, as shown in the sample.  WPF requires this attribute to be added.

**Comment by cwensley** [comment] 2015-12-28 20:48
Hm, sorry I thought you were basing it off my other sample, not the unit tests.. the thread must be created as single threaded, I think you'll have to change it to use System.Threading.Thread instead of the Task factory.

**Comment by cwensley** [comment] 2015-12-28 21:00
So something like this in the TestUtils.Initialize method:

```C#
var thread = new System.Threading.Thread(() =>
{
	try
	{
		var app = new Application(platform);
		app.Initialized += (sender, e) => ev.Set();
		app.Run();
	}
	catch (Exception ex)
	{
		Debug.WriteLine("Error running test application: {0}", ex);
		exception = ex;
		ev.Set();
	}
});
thread.SetApartmentState(ApartmentState.STA);
thread.Start();
```

**Comment by dajuric** [comment] 2015-12-28 21:30
Yes, thank you so much!!
As soon as I verify a few things, I will close the thread. Hope that is OK.
(tomorrow perhaps ?)

Again. It seems to WORK!

**Comment by cwensley** [comment] 2015-12-28 21:31
Great!  no problem. (;
