### ISSUE TITLE
Closable TabControl

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#577] opened 2016-10-12 10:29 UTC
It would be nice if there was a control that has tabs like in VS/MonoDevelop/Any web browser, aka. the ones that can be closed by the user.

**Comment by cwensley** [comment] 2016-10-24 18:21
At least on macOS Sierra, this feature is now available "by default" for any app without any code changes.  Otherwise this is pretty much a dupe of #225 and/or #21

**Closed by cwensley** 2016-10-24 18:21 UTC
Labels: duplicate

**Comment by cra0zy** [comment] 2016-10-24 19:44
Ah, sorry for creating a duplicate issue...

**Comment by cwensley** [comment] 2016-10-24 19:50
@cra0zy no prob, it happens (;
