### ISSUE TITLE
PixelFormat Property

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#514] opened 2016-05-15 15:41 UTC
It would be useful to have the PixelFormat-property readable from Eto.Graphics.Bitmap, because sometimes you need to check, what type of bitmap you have, specially when it was downloaded from some url.

Tom

**Comment by cwensley** [comment] 2016-05-29 04:17
Thanks for submitting the request!

**Comment by cwensley** [comment] 2022-06-11 04:28
Dupe of #642

**Closed by cwensley** 2022-06-11 04:28 UTC
