### ISSUE TITLE
Customize  TabControl

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#680] opened 2017-01-31 21:47 UTC
Would it be possible to customize the TabControl in a way like the tabs in FireFox with a x- and a +-button and also a context-menu on the tab-headers? I think, its modern and common way of adding and removing tabs.

**Comment by cwensley** [comment] 2017-02-01 14:38
Hey, thanks for the report, but this is a duplicate of #225.

**Closed by cwensley** 2017-02-01 14:38 UTC
