### ISSUE TITLE
Font LineHeight inconsistent

### ISSUE THREAD

**Issue by cra0zy** [picoe/Eto#574] opened 2016-10-09 11:58 UTC
Getting font LineHeight is inconsistent between Gtk and Wpf, on Gtk its height wraps around the font but on WPF it only gets the upper part. I'm guessing that the Gtk one is right?

Source: https://gist.github.com/cra0zy/f0ecf04ef273517608a53c46fe1b0c4e

Gtk:
![screenshot from 2016-10-09 13-41-25](https://cloud.githubusercontent.com/assets/6773302/19220201/f7b538d6-8e27-11e6-9482-be4ad9b3c586.png)

Wpf:
![capture](https://cloud.githubusercontent.com/assets/6773302/19220183/96aad122-8e27-11e6-8afc-fd902c298de2.PNG)

CC. @cwensley

**Comment by cwensley** [comment] 2016-10-10 17:54
I think this is because the dimensions returned by the Font object are in _points_, not pixels.  You need to multiply this by the screen's scale to get pixel units.. e.g. `var heightInPixels = font.LineHeight * ParentWindow.Screen.Scale;`

**Comment by cra0zy** [comment] 2016-10-10 19:41
> I think this is because the dimensions returned by the Font object are in points, not pixels. You need to multiply this by the screen's scale to get pixel units.. e.g. var heightInPixels = font.LineHeight * ParentWindow.Screen.Scale;

There would still be inconsistency since Gtk is doing it automatically, but that is not the cause, look at: http://stackoverflow.com/questions/4509613/how-to-calculate-font-height-in-wpf, height seems to be calculated from base line.

**Comment by cwensley** [comment] 2016-12-09 08:01
Hey @cra0zy, I'm closing this as it is working as expected, your sample is assuming that Points == Pixels, which is not the case in WPF.  You need to multiply any of the sizes on the Font object by `Graphics.PointsPerPixels` instead.  Changing your example to this:

```c#
var square = new RectangleF(100, 100, _drawable.Width - 100, font.LineHeight * e.Graphics.PixelsPerPoint);
```

Makes it work as intended.

I have attempted at one point to convert the sizes on the Font object automatically, but this causes problems as not all platforms have a fixed conversion like Windows.  As an example, [Direct2D](https://github.com/mcneel/Eto/blob/develop/Source/Eto.Direct2D/Drawing/GraphicsHandler.cs#L35), [GTK](https://github.com/mcneel/Eto/blob/develop/Source/Eto.Gtk/Drawing/GraphicsHandler.cs#L68), and [macOS](https://github.com/mcneel/Eto/blob/develop/Source/Eto.Mac/Drawing/GraphicsHandler.cs#L249) can have a different size depending on the state of the drawing context.

**Closed by cwensley** 2016-12-09 08:01 UTC
