### ISSUE TITLE
It looks like the Eto.Forms Visual Studio Addin does not support Visual Studio 2019 16.8.2

### ISSUE THREAD

**Issue by AksLev** [picoe/Eto#1834] opened 2020-11-28 08:23 UTC
## Steps to Reproduce the Problem

  1.  Run Eto.Addin.VisualStudio-2.5.8.vsix
  2.  1 hour waiting ...
  3.  Close Form ...
  4.  Run Visual Studio 2019 16.8.2
  5.  New project
  6.  Visual Studio "hanging".

## Code that Demonstrates the Problem

```
[Paste your code here]
```

## Specifications

  - Version:
  - Platform(s): 
  - Operating System(s): Windows 10

**Comment by ElSaico** [comment] 2020-11-28 17:15
This is a duplicate of #1827; in the meantime, as a workaround, you can [create a project via the command line](https://github.com/picoe/Eto/wiki/Quick-Start) and then open it on VS.

**Comment by cwensley** [comment] 2020-12-04 06:21
Closing as dupe

**Closed as completed by cwensley** 2020-12-04 06:21 UTC
