### ISSUE TITLE
[GTK] Wayland not showing program icon

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2255] opened 2022-07-15 12:07 UTC
(KDE) Wayland should show the icon that the program specified.
It works fine on KDE X11.

As far as I'm aware, this is *not* the same as #2115, as KDE on X11 shows it fine without an XDG desktop file:
And an XDG desktop file entry on KDE Wayland also doesn't fix it, while GNOME doesn't show the icon on neither X11 nor Wayland.

## Expected Behavior
The icon should be shown:
![Screenshot_20220715_140432](https://user-images.githubusercontent.com/38186597/179219538-f8ab2b5b-825c-4573-8e79-1ca823fcb7e2.png). 

## Actual Behavior
The default Wayland Icon is shown
![Screenshot_20220715_140812](https://user-images.githubusercontent.com/38186597/179220023-2c8e00eb-9c86-4fe7-bb4b-8bb02286db49.png)

## Steps to Reproduce the Problem

  1. Compile Eto.Test.Gtk for Linux and execute it, or run it from the action builds

## Specifications

  - Version: 2.7.0
  - Platform(s): Eto.GTK
  - Specs: 
Operating System: Arch Linux
KDE Plasma Version: 5.25.3
Graphics Platform: Wayland
GTK Theme: Breeze

## Notes
It may be that this is actually a KDE issue, and not an Eto issue.
A possible workaround is to force the application to run in X11 via the `GDK_BACKEND=x11` environment variable.

**Comment by tewkanz** [comment] 2022-08-07 09:08
It's not a bug, per se, but it does expose a limitation of Eto. When Gtk is used, Eto creates a GApplication without specifying the name:
```
protected override void Initialize()
{
	base.Initialize();
	Helper.Init();

	if (SynchronizationContext.Current == null)
		SynchronizationContext.SetSynchronizationContext(new GtkSynchronizationContext());

#if GTK3
	Control = new Gtk.Application(null, GLib.ApplicationFlags.None);
	Control.Register(GLib.Cancellable.Current);
	Helper.UseHeaderBar = true;
#else
	Helper.UseHeaderBar = false;
#endif
}
```

This is a problem for Wayland desktop environments because they use the GTK application name to map the window to a .desktop file that specifies which icon should be shown. Eto should give you a way to set this.

There's a little bit of detail here:
[Fixing Wayland taskbar icons](https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/)

Based on what I've seen, GTK Sharp defaults the application name to the assembly creating the application. So, as a workaround, you can create a .desktop file with the same name as the assembly. At least, that worked for me with the [OpenTabletDriver](https://github.com/OpenTabletDriver/OpenTabletDriver) project. The icon started showing when I renamed the desktop file `OpenTabletDriver.UX.Gtk.desktop`

**Comment by Miepee** [comment] 2022-08-07 10:15
Thanks for digging all of that up! Wasn't aware that so many things rely on a .desktop file nowadays.

**Comment by cwensley** [comment] 2023-03-17 07:41
I'm not seeing this issue in Ubuntu 22.04 using Wayland.  Is this an Arch Linux issue?

**Comment by Miepee** [comment] 2023-03-17 10:46
No, I'm having the same issue on openSUSE Tumbleweed with GNOME 43.3

![image](https://user-images.githubusercontent.com/38186597/225883569-cffa295b-2b1d-4ab1-8b12-9a977c633002.png)


And also under KDE 5.27.2
![grafik](https://user-images.githubusercontent.com/38186597/225884625-c9bd931f-d967-4eb4-a60f-5d72e85bf0e7.png)


But considering that this is more of a Wayland limitation (since the DEs just use the name to map it to a desktop file which in case of Eto.Test does not exist), the issue should probably be closed.

**Comment by cwensley** [comment] 2023-11-17 21:09
Closing as suggested since this isn't something that Eto can do, it's part of the distribution of the app.

**Closed as completed by cwensley** 2023-11-17 21:09 UTC
