### ISSUE TITLE
Issue with Label inside Table/Dynamic Layout in GTK 

### ISSUE THREAD

**Issue by DanWBR** [picoe/Eto#842] opened 2017-08-01 12:40 UTC
If you try the following layout code in GTK:

`            

            var table = new TableLayout();
            var cellcp = new Panel();
            var txtcell = new TextBox { Width = 80, ReadOnly = true };
            var txttype = new TextBox { Width = 200, ReadOnly = true };
            var txtformula = new TextBox() { PlaceholderText = "To enter a formula,  type '=' followed by the math expression and press ENTER to commit changes." };
            var btnImport = new Button { Text = "Import" };
            var btnExport = new Button { Text = "Export" };
            var btnClear = new Button { Text = "Clear" };
            var btnEvaluate = new Button { Text = "Evaluate" };
            var btnEvaluateAll = new Button { Text = "Evaluate All" };

            var tr = new TableRow(new Label { Text = "Selected Cell", VerticalAlignment = VerticalAlignment.Center }, txtcell,
                                    new Label { Text = "Type", VerticalAlignment = VerticalAlignment.Center }, txttype,
                                    new Label { Text = "Contents", VerticalAlignment = VerticalAlignment.Center }, txtformula,
                                    btnImport, btnExport, btnClear, btnEvaluate, btnEvaluateAll);

            tr.Cells[5].ScaleWidth = true;

            var tb = new TableLayout { Spacing = new Size(5, 5), Padding = new Padding(10) };
            tb.Rows.Add(tr);
            
            cellcp.Content = tb;

            table.Rows.Add(new TableRow(cellcp));

            var dl = new DynamicLayout { Padding = new Padding(10, 0) };

		var longtext = new Label { Text =  "Select cells by clicking or touching on them (using arrow keys on the keyboard won't change the currently selected data cell). After selecting the cell, edit its contents on the 'Contents' input box, or configure it to import or export data from/to the flowsheet by clicking on the corresponding buttons.", Wrap = WrapMode.Word, Font = SystemFonts.Label(SystemFonts.Default().Size - 2.0f) }

		dl.AddRow(new TableRow(longtext));
            
            table.Rows.Add(new TableRow(dl));

            table.Rows.Add(new TableRow(new Scrollable { Content = new Panel(), Border = BorderType.None }));

            return table;`

you'll see that, upon form showing, the 'longtext' Label will be sized to occupy only the first column on the table, even if the rows aren't contained in the same table. As soon as you manually resize the form, the label stretches itself to occupy the entire row, as expected. This doesn't happen on WPF/MonoMac (the label already fills the row when the form is shown).

**Comment by DanWBR** [comment] 2017-08-01 12:49
This is the expected behavior (WPF):

![clipboard02](https://user-images.githubusercontent.com/2669419/28825974-47ce9504-7696-11e7-85c1-4618fa44ec7d.jpg)

**Comment by DanWBR** [comment] 2017-08-01 13:02
This is on GTK when the form is first shown:
![captura de tela 2017-08-01 as 08 55 38](https://user-images.githubusercontent.com/2669419/28826419-18988e28-7698-11e7-9082-f309c1926e6c.png)
After resizing:
![captura de tela 2017-08-01 as 08 55 51](https://user-images.githubusercontent.com/2669419/28826440-2b70e734-7698-11e7-96d0-e7b07b2b4756.png)

**Comment by DanWBR** [comment] 2017-08-01 13:04
On MonoMac:
![captura de tela 2017-08-01 as 08 59 31](https://user-images.githubusercontent.com/2669419/28826493-587ec4e4-7698-11e7-805f-355d017a32d9.png)

**Comment by SlowLogicBoy** [comment] 2017-08-01 13:06
try label.Invalidate() after it is shown. Probably after form is shown and sizes changes, label is not invalidated. @cra0zy could probably tell more about this.

**Comment by cwensley** [comment] 2017-08-01 16:55
Thanks for reporting the issue!  Is this Gtk2 or 3?

**Comment by DanWBR** [comment] 2017-08-01 17:03
GTK 2.

**Comment by cra0zy** [comment] 2017-08-01 17:33
> @cra0zy could probably tell more about this.

Surprisingly enough I can't :/ The label wrap code for Gtk is very very messed up in the Eto source, now for the NativeGtk port I am working on I did get the label wrap properly working, tho what I did was basically delete the entire class and write it from scratch (also I got height a bit bugged up because of some other pieces of code).

**Comment by cwensley** [comment] 2017-08-01 17:36
@DanWBR also give Eto 2.4 a try from the myget feed I pointed to earlier (it's also on the README).  There have been some fixes regarding that for Gtk2.

**Comment by DanWBR** [comment] 2017-08-01 17:37
@cra0zy this is not that big, if you increase the form's width by 1 programmatically after showing the form it already layouts itself as expected, maybe Invalidate() will do the trick.

**Comment by DanWBR** [comment] 2017-08-01 17:38
@cwensley I'll do that ASAP.

**Comment by cra0zy** [comment] 2017-08-01 18:05
@DanWBR Actually Label wrapping is not working at all on Eto.Gtk3 side. (also do note that you should probably not be using Eto.Gtk2 for Linux, it's using the version of Gtk that has been in bugfix only mode since 2011, the only reason why Eto is still keeping it around is because MonoDevelop is still using it).

**Comment by DanWBR** [comment] 2017-08-01 18:31
@cra0zy I'll take that into account, actually I couldn't get Gtk3 running on my linux VM so I went the Gtk2 way. It is working nicely so far.

Personally, I think you guys should not remove any of the created platforms so far (I saw some early discussion about removing MonoMac, etc). Even if you're not mantaining them anymore, they may still be useful for someone out there. MonoMac is very very practical because you only need a single DLL and my macOS "native" library can still be compiled on Windows.

DWSIM (the software I'm porting to Eto) is currently Windows Forms only, and it runs on Linux through Mono's port (screenshot here: https://upload.wikimedia.org/wikipedia/commons/3/34/DWSIM_v3_running_on_Ubuntu_Linux.jpg). Note that support for WinForms on Mono was "abandoned" years ago, but it still *just* works! There are some minor bugs which we I live with.

 I'm a chemical engineer and we (plant engineers) use "old" stuff a lot in your daily work because they just work, and we also know how to live/deal with their issues very well. Like Windows XP. :-) - kidding haha

**Comment by cwensley** [comment] 2017-08-01 18:43
@DanWBR fwiw, we can use Xamarin.Mac.dll the same way we use MonoMac.dll. I'm hoping to update the nuget packages to use this in the future, and it should work the same way so you can still build on windows and run on Mac (with mono installed).

**Comment by cra0zy** [comment] 2017-08-01 18:50
> @cra0zy I'll take that into account, actually I couldn't get Gtk3 running on my linux VM so I went the Gtk2 way. It is working nicely so far.

You need to install `gtk-sharp3` package, `gtk-sharp` package that Eto.Gtk requires is a dependency of MonoDevelop so you didn't even notice that you needed a dependency for it as well. I am currently working on Eto.NativeGtk which will skip gtk-sharp wrappers and call gtk functions directly, which will remove redundant dependency as well as make it much easier for us to maintain Eto.NativeGtk for the newer versions of Gtk (Gtk 4 is on the way, and gtk-sharp3 still hasn't even been officially released...)

> Personally, I think you guys should not remove any of the created platforms so far (I saw some early discussion about removing MonoMac, etc). Even if you're not mantaining them anymore, they may still be useful for someone out there. MonoMac is very very practical because you only need a single DLL and my macOS "native" library can still be compiled on Windows.
> 
> DWSIM (the software I'm porting to Eto) is currently Windows Forms only, and it runs on Linux through Mono's port (screenshot here: https://upload.wikimedia.org/wikipedia/commons/3/34/DWSIM_v3_running_on_Ubuntu_Linux.jpg). Note that support for WinForms on Mono was "abandoned" years ago, but it still just works! There are some minor bugs which we can live with...

You can just use an older version of Eto that supported the old platform you needed, the point of dropping platforms is that there are better options out there, and that there is no point in wasting time trying to support them.

> I'm a chemical engineer and we (plant engineers) use "old" stuff a lot in your daily work because they just work, and we also know how to live/deal with their issues very well. Like Windows XP. :-) - kidding haha

https://twitter.com/MrDBCross/status/491621667408334848

**Comment by DanWBR** [comment] 2017-08-01 19:03
> You can just use an older version of Eto that supported the old platform you needed, the point of dropping platforms is that there are better options out there, and that there is no point in wasting time trying to support them.

Maybe you don't actually need to support old stuff. Just leave it there...

**Comment by cra0zy** [comment] 2017-08-01 19:04
> Maybe you don't actually need to support old stuff. Just leave it there...

3 PRs after it will start failing to compile...

**Comment by DanWBR** [comment] 2017-08-01 19:05
Back to the issue, I can confirm that v2.4.0 on MyGet fixes it:

![captura de tela 2017-08-01 as 14 51 36](https://user-images.githubusercontent.com/2669419/28842194-b4f87828-76ca-11e7-93b0-51da398f3df1.png)

BUT you've introduced another issue (GTK-specific) on DropDown list items. They are being truncated for some strange reason:

![captura de tela 2017-08-01 as 14 52 51](https://user-images.githubusercontent.com/2669419/28842210-c1149902-76ca-11e7-9fc3-26029bd9bdc2.png)

**Comment by DanWBR** [comment] 2017-08-01 19:18
> I am currently working on Eto.NativeGtk which will skip gtk-sharp wrappers and call gtk functions directly, which will remove redundant dependency as well as make it much easier for us to maintain Eto.NativeGtk for the newer versions of Gtk (Gtk 4 is on the way, and gtk-sharp3 still hasn't even been officially released...)

@cra0zy maybe I should port my app to every single Eto platform currently available - the more options, the better, and I'm always looking for new stuff to learn about. The only relevant issue for me is to get SkiaSharp working on the remaining platforms. GTK on Linux was the hardest one because you have to compile the native Skia library for yourself.

**Comment by cra0zy** [comment] 2017-08-01 19:20
Hmm.. I wasn't able to replicate that, first letters still do start getting drawn for me:

![smallwidth](https://user-images.githubusercontent.com/6773302/28842651-c4843212-76fe-11e7-9c4b-44c1a8fdc1a6.png)

**Comment by DanWBR** [comment] 2017-08-01 19:31
@cra0zy try a longer string. In my case that shouldn't be happening anyway, check the size of my DropDown... this is what I expect and was working correctly with v2.3.0:

![clipboard03](https://user-images.githubusercontent.com/2669419/28843230-6bcfb964-76ce-11e7-9bd8-5a2f7bdaf96f.jpg)

**Comment by cra0zy** [comment] 2017-08-01 19:39
Works fine for me, try not setting the `Width` or `Size` of your dropdown.

**Comment by cwensley** [comment] 2017-08-01 19:48
@DanWBR perhaps open a separate issue for the drop down problem with a little sample that reproduces it?  If it worked in 2.3, it'd be nice if it weren't broken for no good reason.  It appears from your screenshot that the width of the popup is correct (ish), so it should at least show something.

**Comment by DanWBR** [comment] 2017-08-01 20:18
@cwensley I'll create a new issue for that.

**Comment by cwensley** [comment] 2017-08-09 17:05
I think this one was verified that it is fixed in the develop branch so marking as such.  Thanks again for the report!

**Closed by cwensley** 2017-08-09 17:05 UTC

**Comment by DanWBR** [comment] 2017-08-09 17:23
Confirmed fixed in v2.4+.
