### ISSUE TITLE
Drag selection on GridView gets stuck on XamMac2

### ISSUE THREAD

**Issue by m-tapper** [picoe/Eto#1596] opened 2020-02-24 15:48 UTC
## Problem

There seems to be a problem with performing drag selections on Grid Views for the Mac. The SelectedItem notifications will become stuck on the first item selected when starting a drag and continually report the same item as selected for all future notifications.

## Steps to Reproduce the Problem

I have managed to reproduce the problem with the Eto.Test.XamMac2 app
  1. Open the Behaviours / Drag and Drop section
  2. Selecting individual items on the Grid View Drag source with report the selected item in the log
  3. Starting on an item which is not currently selected perform a drag to select multiple items.
  4. The log will report the first item selected during the drag but will continue to report that same item for all future selection changes.

## Code Investigation
What seems to be happening is the DraggingSessionEnded method of EtoTableViewDataSource is not being called when the drag is completed so the handler CustomSelectedRows property is not being cleared. So the selection change notifications keep reporting the CustomSelectedRows value.

**Comment by cwensley** [comment] 2020-02-24 18:56
Hey @m-tapper, thanks for reporting the issue _and_ investigating the cause.  That should make it much easier to fix!

**Comment by cwensley** [comment] 2020-03-19 05:33
This should now be fixed and will be included in 2.5.1.  Thanks again!!

**Closed as completed** 2020-03-19 05:32 UTC
