### ISSUE TITLE
Form.Screen is null in OnLoad, ok in OnShown (Linux only)

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1587] opened 2020-02-21 01:22 UTC
It used to be that we could center and size a form before displaying it by overriding `OnLoad` and accessing the `form.Screen` property.

However, `form.Screen` is now `null` until the form is shown and, thus, only available until `OnShown` is called.

This is rather undesirable and only an issue on Linux (perhaps Mac too).

**Comment by LaraSQP** [comment] 2020-02-22 06:40
Dialogs also fail to have the `Screen` property filled until `OnShow`.

This should, and used to, happen before `OnLoad`.

Please look into the issue.

Thank you.

**Comment by cwensley** [comment] 2020-06-15 08:55
Hey @LaraSQP, yes the Screen property is null until the form is actually shown.

This is the same on most (all?) platforms. It wasn't a problem before on GTK because it was actually showing the form before it was fully loaded afaik.

You can use the `Screen.PrimaryScreen` or `Screen.Screens` to get the screens that are available before you show your form.  If you're showing it from a parent window, use the Screen property of that parent window to determine which screen it should be shown from.

I'm closing this as this is expected behaviour.

**Closed as completed by cwensley** 2020-06-15 08:55 UTC

**Comment by LaraSQP** [comment] 2020-06-15 09:02
Thanks for looking into this and for the workaround.
