### ISSUE TITLE
Toolbars

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#907] opened 2017-10-25 10:41 UTC
We are reaching the point now with the current project, where we really need additional toolbars, not only in main-window. Is this something to expect soon? 
And on the Mac-side [this issue](https://github.com/picoe/Eto/issues/889) is still unsolved but important.

Thanks
Tom

**Comment by cwensley** [comment] 2017-10-25 16:34
Hey, thanks for reporting the issue but it's a duplicate of #339.

Unfortunately it is not on my short term list, so contributions on that are welcome.  #340 has some flaws in the design and only implements the functionality for WinForms and Gtk, but it might be a good starting point.

**Closed by cwensley** 2017-10-25 16:34 UTC
