### ISSUE TITLE
Unknown solution item type: MonoMac

### ISSUE THREAD

**Issue by ghost** [picoe/Eto#582] opened 2016-10-15 06:18 UTC
When creating a new Eto.Forms solution from MonoDevelop on Linux or Xamarin Studio Community on Windows, I get the following the error: `Unknown solution item type: MonoMac`. This stops all project creation.

This error reappears again when loading the previewer in existing Eto.Forms projects. It doesn't stop development but it does disable the previewer.

On semi-related note to #579, Eto.Forms _does not_ crash either version of the IDE on either platforms - Xamarin guys know how to code. Which is why I tried their IDE in the first place.
- Xamarin Studio Community 6.1.1, build 15, from Windows
- MonoDevelop 6.1.1, build 15-1, from Linux

**Comment by claunia** [comment] 2016-10-16 16:48
Seems that Xwt suffers from the same so maybe it's an upstream problem?

**Comment by SkyrisBactera** [comment] 2016-10-18 01:10
I can confirm this. I was able to get around it by using an older version of MonoDevelop (5.10) from the Mono PPA. Unfortunately, this version's code preview is broken on my computer.

**Comment by cwensley** [comment] 2016-10-24 18:09
Thanks for reporting the issue!  Looks like I'll have to put a conditional on creating the monomac project.  Ugh.

**Comment by claunia** [comment] 2016-10-26 03:11
@cwensley good, but would that leave Eto.Mac out of the equation ? I have not tested but I got the impression that compiling on Linux/Win created an executable able to open Eto.Mac when running in OSX.

Good news, bug has been assigned upstream.

**Comment by cwensley** [comment] 2016-10-27 15:20
This is currently how the VS addin works as well, since it can't create the MonoMac or Xamarin.Mac projects either.

**Comment by darkoverlordofdata** [comment] 2016-11-08 20:20
I'm getting the same issue. Is there a way to just disable Mac support? All I'm interested in is Win/Linux, I'd be throwing away the mac version anyway...

**Comment by adityaka** [comment] 2016-12-26 18:06
I was able to work around this in Xamarin Studio Community 6.1.3 buid 19. The template files  in the ETO forms addin library 

%userprofile%\AppData\Local\XamarinStudio-6.0\LocalInstall\Addins\Eto.Addin.XamarinStudio.2.3.0.6\Templates\Projects\CS\application.xpt.xml

Commented the MAC projects line#192-265 


I am now able to create and build a ETO app in the Xamrin studio with desktop solution 
Haven't tested linux yet check the screenshot below. 
![image](https://cloud.githubusercontent.com/assets/1608749/21485142/1227797a-cbc4-11e6-901d-6f01a7a7ff53.png)

**Comment by nsmarkop** [comment] 2016-12-26 19:42
I did the same with the F# project template on Linux and it builds and runs now.

![image](https://cloud.githubusercontent.com/assets/4577561/21485867/f477069c-cb6f-11e6-93c6-a58fc28473d1.png)

I'm on Ubuntu 16.10 with MonoDevelop 6.1.2 and using `locate application.xpt.xml` I was able to find my templates at (replace FS with CS or VB):

/home/USER/.var/app/com.xamarin.MonoDevelop/data/MonoDevelop-6.0/LocalInstall/Addins/Eto.Addin.XamarinStudio.2.3.0.6/Templates/Projects/FS/application.xpt.xml

**Comment by adityaka** [comment] 2016-12-26 19:50
for monodevelp 6.1.2 on a mint linux installed over a flatpak the same file can be located under 
$HOME/.var/app/com.xamarin.MonoDevelop/data/MonoDevelop-6.0/LocalInstall/Addins/Eto.Addin.XamarinStudio.2.3.0.6/Templates/Projects/CS/

The edits are similar to what we did on windows 
![image](https://cloud.githubusercontent.com/assets/1608749/21486010/74a3b34e-cbd2-11e6-8eb3-2638336f774e.png)

PS I am editing the windows post as well we need to change line # 23  to make the desktop project as startup object 

		<Options>
			<StartupProject>${ProjectName}.Desktop</StartupProject>
		</Options>

**Comment by cwensley** [comment] 2018-02-01 11:32
Should now be fixed with #974 now that it uses a dotnet template which doesn't require such integration with the IDE.  However, I would still suggest to use VS on windows (which hasn't been updated yet but soon!)

A new version of the addin will be published along with the 2.4 release, or you can build it manually.

**Closed by cwensley** 2018-02-01 11:32 UTC
