### ISSUE TITLE
[Mac] controls not correctly positioned in the PixelLayout

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1317] opened 2019-02-08 14:43 UTC
I have a regression with my splash screen since commit 2da1cdc, where my controls are no longer positioned correctly on a PixelLayout.
Basically I use a PixelLayout to display a logo in background and some texts that I set while loading the rest of the application.
I managed to only partially reproduce the regression with the following repro.

## Expected Behavior
![image](https://user-images.githubusercontent.com/21080030/52471985-851cfd80-2b92-11e9-92c7-5e26047d38b7.png)
(actually in my real splash the texts "Version", "Copyright" and "Feedback" are fully written, but that probably depends on the fact that they are written only later on, while the application is loading)

## Actual Behavior
![image](https://user-images.githubusercontent.com/21080030/52471932-6454a800-2b92-11e9-8165-4e3f19419da4.png)
As you can see "Version", "Copyright" and "Feedback" are wrongly position (16 pixels above the correct position), while "VersionType" is correctly positioned.
In my real splash the white is also painted a bunch of pixels beyond the bottom of the form, what differs from the repro is that the bitmap is loaded rather than created. I tried to load the image as in my real app but (shame on me) I failed miserably ;)

## Steps to Reproduce the Problem

  1. Run the following repro code

## Code that Demonstrates the Problem

```
using System;
using Eto;
using Eto.Drawing;
using Eto.Forms;
namespace Test
{
	public class Program
	{
		[STAThread]
		public static void Main(string[] args)
		{
			var app = new Application(Platform.Detect);
			var form = new Splash();
			app.Run(form);
		}
	}

	public partial class Splash : Form
	{
		PixelLayout pl;
		Bitmap bmpLogo;
		ImageView imvLogo;
		Label lblVersion;
		Label lblCopyright;
		Label lblVersionType;
		Label lblFeedback;

		public Splash()
		{
			WindowStyle = WindowStyle.None;
			Resizable = false;

			//var bmpLogo = Bitmap.FromResource("Test.logo.png");
			var bmpLogo = new Bitmap(600, 300, PixelFormat.Format32bppRgba);
			using (var g = new Graphics(bmpLogo))
			{
				for (int x = 0; x < 600; x += 50)
					g.DrawLine(Colors.Green, x, 0, x, 299);
				for (int y = 0; y < 300; y += 50)
					g.DrawLine(Colors.Green, 0, y, 599, y);
			}
			//bmpLogo.Save("logo", ImageFormat.Png);

			imvLogo = new ImageView { Image = bmpLogo, Size = new Size(600, 300) };
			lblVersion = new Label() { Text = "Version" };
			lblCopyright = new Label() { Text = "Copyright" };
			lblFeedback = new Label() { Text = "Feedback" };
			lblVersionType = new Label() { Text = "VersionType", Size = new Size(405, 20), TextAlignment = TextAlignment.Right, Font = new Font("Arial", 16) };

			pl = new PixelLayout();
			pl.BackgroundColor = Colors.White;
			pl.Add(imvLogo, new Point(0, 0));
			pl.Add(lblVersion, new Point(12, 9));
			pl.Add(lblCopyright, new Point(12, 25));
			pl.Add(lblFeedback, new Point(65, 273));
			pl.Add(lblVersionType, new Point(139, 267));
			Content = pl;
		}
	}
}
```

## Specifications

  - Version: develop after comit 2da1cdc
  - Platform(s): XamMac2
  - Operating System(s): macOS 10.13.4

**Comment by cwensley** [comment] 2019-02-09 10:37
Thanks for reporting the issue!  I think this is a duplicate of #1316, even though it is reproduced with different code.

**Closed as completed** 2019-02-09 10:51 UTC
