### ISSUE TITLE
GTK: GroupBox border was missing on Linux

### ISSUE THREAD

**Issue by LiYouR** [picoe/Eto#2186] opened 2022-04-11 07:12 UTC
![image](https://user-images.githubusercontent.com/37136890/162683956-bf42aee7-1575-4fde-927a-b047c92876e6.png)

**Comment by cwensley** [comment] 2022-04-22 15:53
This is likely a GTK style/theme issue.  Please check which GTK theme you are using to ensure its Frame control includes a border.  See https://stackoverflow.com/a/13266308/981187 for some information about that.

**Comment by Miepee** [comment] 2022-07-15 12:52
The border shows up fine for me with Breeze as the GTK theme.

Based on the screenshot, it looks like that's Deepin. I installed its [GTK theme](https://github.com/linuxdeepin/deepin-gtk-theme), but also cannot reproduce missing borders there. Either it was fixed in the few months, or it only happens on Deepin, in which case you should submit an issue to them.

**Comment by cwensley** [comment] 2023-03-17 07:18
Closing a the is not an Eto issue.

**Closed as completed by cwensley** 2023-03-17 07:18 UTC
