### ISSUE TITLE
[Mac] Form content is blank

### ISSUE THREAD

**Issue by msasso69** [picoe/Eto#1134] opened 2018-06-17 10:13 UTC
Dear Curtis,

I'm developing on a VM with OSX 10.13.5 and testing from time to time with my wife's Mac with OSX 10.9.5,
It was quite a while that I was not testing anymore on my wife's mac and I recently found out that on it my forms and dialogs are now always empty.

I then tried with the Eto.Test application: same result, only the menu is rendered.

I cannot tell you what Eto pull made my wife's computer stop rendering Eto.Forms correctly, I can only say that recently I noticed the same beviour on OSX10.13.5 but you fixed it right before I was about to raise an issue (maybe it can help?), unfortunately on OSX10.9.5 still remains.

From the Wiki I see that the minimum supported platform is OSX 10.7 or greater. Is it still like that?

Thanks for your help

## Specifications

  - Version: pulled Eto code 17th June 2018
  - Platform(s): Mac, Mac64, XamMac2
  - Operating System(s): macOS 10.9.5

**Comment by MartinRothschink** [comment] 2018-06-18 06:48
Which version of Mono is involved on both machines?

**Comment by msasso69** [comment] 2018-06-19 09:01
in the development machine (a VM) with osx 10.13.5 I have a mono 5.8.1
in the test machine (a physical machine) with osx 10.9.5 I installed a mono 5.10.1.47

@MartinRothschink, I assume that XamMac2 should work regardless of if and what version of mono is installed, am I right? In fact I also tried to remove all mono versions in the machine (in the past I had mono 4.8.1) and if I remember well the Eto.Test application still started but with all the forms empty.

**Comment by msasso69** [comment] 2018-06-25 19:56
Thanks Curtis,
in the meantime I'll try to get my hands on other Mac OS versions and test also on them.

**Comment by cwensley** [comment] 2018-06-25 22:57
@msasso69 btw, PR #1139 *might* fix the issue for you, though it was for unrelated reasons it might have an impact on this as well.  Is your form auto sized or are you assigning it a size/client size before being shown?

**Comment by msasso69** [comment] 2018-07-10 16:50
With today pull (10th July) thing are little better but still not working: now the menu is visible (as before) as well as the left navigation panel (I'm talking about the Eto.Test application), but the main forms are still blank :(

**Comment by cwensley** [comment] 2018-07-10 16:54
Hey @msasso69, thanks for the update.  I have replicated this with older versions of macOS and there's definitely something that needs fixing here.  I tried a few things to see if I can get it working quickly (which helped a little) but it looks like it'll take a bit more work.  This will need to be fixed for the 2.5 release.

**Comment by msasso69** [comment] 2018-07-10 17:03
Thanks!

**Comment by cwensley** [comment] 2018-11-16 16:34
Hey @DanWBR, thanks for the poke.  There's no ETA other than it is on the 2.5 milestone.  I'll see if I can find time to get to this sooner rather than later.

**Closed** 2019-02-03 22:53 UTC

**Comment by cwensley** [comment] 2019-02-03 23:00
Hey @msasso69, thanks again for reporting the issue!  I assumed this all worked the same as the api's I used were introduced in macOS 10.7.  It appears that just adding a single constraint to the window's content view made everything work as expected, along with other fixes with newly introduce api's that were used.

After these changes, there are still a few redraw glitches in 10.7 and 10.8. However, 10.9+ appears to work flawlessly and considering other software only supports 10.9+ now (Xamarin.Mac, mono 5.18, etc), I think this is acceptable.

Give it a try and let me know if you run into any issues with the new changes.

Cheers!

**Comment by msasso69** [comment] 2019-02-04 11:42
Hi Curtis, great news you found a way to fix the issue! 
Unfortunately it does not work with my application :(
All my panels containing GridView(s) or TreeGridView(s) went bananas (tested on High Sierra, I haven't tried it yet on my old Mac).
Trees and grids either disappeared or look empty and with a wrong size :(
I'll try to narrow down the problem in order to give you a reproducible snippet of code, but in the meantime I'll revert my Eto code to commit 8eb0acb (I pull once in month, and I assume that the fix is in commit 0b916d6 and 3a5e3e2).
Anyway thanks for your effort, I appreciate!

**Comment by cwensley** [comment] 2019-02-04 17:34
@msasso69 thanks for testing it out!  Sorry to hear it's not working for you.  It's pretty weird as the Eto.Test application appears to work fine for 10.9 all the way through 10.14.

**Comment by msasso69** [comment] 2019-02-04 17:35
Little update: the commit that screwed the layout of my app on my Mac 10.13.4 is ffa533d (or 2da1cdc), with 5de53c1 it went back to normal

**Comment by cwensley** [comment] 2019-02-04 17:37
@msasso69 ah, good to know!  Please file a separate issue with a repro if you can, I can't seem to reproduce it myself.

**Comment by msasso69** [comment] 2019-02-04 17:38
I haven't seen what happens with the Eto.Test in my machine, because I still suffer of #1289, I cleaned with git, didn't work, I still have to update VS, tonight I'll do it.

**Comment by msasso69** [comment] 2019-02-04 17:40
Ok, I'll try to make a separate repro. Sorry If I do not answer in sync and I mix up the messages! ;)

**Comment by msasso69** [comment] 2019-02-06 11:01
I think I found the catch, and I managed to reproduce the problem in a simple repro, but I'm not sure whether it is a regression in Eto or if I was mis-using the PixelLayout.
Basically many of my controls (mainly grids and trees) are added to a PixelLayout together with a progress bar that I make visible when loading lots of data.
In order to fit my controls to the size of the PixelLayout I am also sizing them on the SizeChanged event of the PixelLayout.
After commit 2da1cdc I also need to reposition my controls after sizing them, otherwise their location go bananas :)
If you think it's a regression I can post a simple repro in a new issue.
I also have another regression in my splash, I still have to investigate it but I have the feeling that if a Form does not have a border the position in the PixelLayout is not taking into account the absence of the caption.

**Comment by cwensley** [comment] 2019-02-06 14:33
Hey @msasso69,

That definitely sounds like a regression.  The position of the control shouldn't change when you change a control's size.  Posting a repro in a new issue would be extremely helpful, and can add to the tests I use to make sure things aren't broken in the future.

**Comment by msasso69** [comment] 2019-02-08 14:49
I confirm that this issue is closed, the regressions I have are separate issues. Thanks for the great job!
