### ISSUE TITLE
Xaml User Controls

### ISSUE THREAD

**Issue by grbd** [picoe/Eto#443] opened 2016-01-15 11:51 UTC
Hi,
I was wondering if it would be okay if I added some xaml examples to the wiki
One thing I have tried which seems to work is embedding one xaml control inside another
but I didn't find any docs on how to do this within Eto.Forms

For example

Panel1.xeto
```
<?xml version="1.0" encoding="UTF-8"?>
<Panel
  xmlns="http://schema.picoe.ca/eto.forms" 
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  >
	<Label Text="Panel1" />
</Panel>
```

MainForm.xeto
```
<?xml version="1.0" encoding="UTF-8"?>
<Form
	xmlns="http://schema.picoe.ca/eto.forms" 
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="clr-namespace:TestApp;assembly=TestApp"
  Title="My Eto Form"
	ClientSize="400, 350"
	>

  <TableLayout>
    <TableRow>
      <TableCell>
        <local:Panel1></local:Panel1>
      </TableCell>
    </TableRow>

  </TableLayout>
</Form>
```

The key lines are
```
xmlns:local="clr-namespace:TestApp;assembly=TestApp"
```
and making sure to use the prefix
```
<local:Panel1></local:Panel1>
```

In theory if both controls are in the same assembly, it should be possible to ommit the ;assembly=TestApp part of the string or just use assembly=, but it looks like it's required with the current version of the Xaml library in use.

Also for a while I was getting some sort of strange Content equals null error in the preview window when I first tried this, although that seems to have fixed itself now

**Comment by cwensley** [comment] 2016-01-15 18:07
@grbd, yes adding samples and general help for xaml to the wiki would be very welcome!

It'd also be nice if the samples were added to the [Samples.sln](https://github.com/picoe/Eto/blob/develop/Samples/Samples.sln) so they can be tested out.

**Comment by cwensley** [comment] 2016-04-25 21:16
Closing as the issue is a question, which I think has been answered.  Please feel free to comment/reopen if needed.

**Closed by cwensley** 2016-04-25 21:16 UTC
