### ISSUE TITLE
.NET Core 3.1 sets up .NET standard 2.0 projects for libraries

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto#1547] opened 2020-01-04 14:59 UTC
## Expected Behavior

Project files are set to be .NET Core 3.1

## Actual Behavior

Project files are set to use the .NET standard 2.0.

## Steps to Reproduce the Problem
Confirm the dotnet version installed : 
dotnet --version
3.1.100

For the 3.1 version installed, do:

  1. dotnet new -i "Eto.Forms.Templates::2.5.0-ci-10403" --nuget-source https://www.myget.org/F/eto/api/v3/index.json
  2. dotnet new etoapp -sln -s -m code -wf
OR
  2. dotnet new etoapp -sln -m code -wf

Review the resulting project files for the library :

```
<Project Sdk="Microsoft.NET.Sdk">
        
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>nc31</RootNamespace>
    <PackageVersion>1.0</PackageVersion>
    <Title>nc31</Title>
    <Copyright>Copyright © 2019</Copyright>
    <Description>Description of nc31</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.5.0-ci-10403" />
  </ItemGroup>
  
</Project>
```

Should TargetFramework be netcoreapp3.1

## Specifications

  - Version: 2.5.0-ci-10403
  - Platform(s): All
  - Operating System(s): All
  
[nc31_linux.zip](https://github.com/picoe/Eto/files/4022038/nc31_linux.zip)

**Comment by cwensley** [comment] 2020-01-06 16:23
Hey @philstopford this is correct, the library should be .NET Standard 2.0, which is consumable by any of the launchers (net461, or in the future netcoreappX).

**Comment by cwensley** [comment] 2020-01-09 08:45
Closing this as this is the intended behaviour here.

**Closed as completed by cwensley** 2020-01-09 08:45 UTC
