### ISSUE TITLE
App Closes unexpectedly while Main is hidden.

### ISSUE THREAD

**Issue by kedrin** [picoe/Eto#1187] opened 2018-08-27 22:10 UTC
## Expected Behavior
Application continues running while main form is hidden

## Actual Behavior
Application exits when main form is hidden and secondary window is closed. This occurs on GTK3 on linux and Windows, Wpf operates as expected. This occurs even when the application main form is set or started with app.run(new Form());

## Steps to Reproduce the Problem
On the GTK3 platform with a tray indicator icon the main window is hidden on close, a dialog is opened through the tray icons context menu. When closing the dialog the application exits as if the main window was closed.

## Code that Demonstrates the Problem

https://github.com/kedrin/ETOAppClosureError

  - Version: 4.2.1
  - Platform(s): WPF, Gtk3
  - Operating System(s):  Windows 10 Ubuntu 18.04

**Comment by cwensley** [comment] 2018-08-30 03:45
Thanks for reporting the issue!

**Comment by MartinRothschink** [comment] 2018-10-04 08:27
This is a duplicate of my issue #1132

**Closed** 2018-10-05 09:06 UTC
