### ISSUE TITLE
Application.Instance.Open crashing on Gtk (and possibly MacOS?)

### ISSUE THREAD

**Issue by ManuelHu** [picoe/Eto#1700] opened 2020-05-28 09:06 UTC
On current Mono versions `Application.Instance.Open` does not work and crashes, despite the changes in ff54cf5.

The cause is *probably* the following corefx issue: dotnet/runtime#17938. I suppose the upstream changes causing this issue got merged into Mono as well, because they try to incorporate more parts of corefx/coreclr.

The "old" (still not deprecated but crashing) approach of using `UseShellExecute = true` worked until a couple of mono versions ago, but broke afterwards... The current Ubuntu-bundled mono is definitely broken. On dotnet core it has never worked, as far as I know.

## Expected Behavior
The given URL will be opened and the app does not crash.

## Actual Behavior
It throws the following exception:
```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo) [0x00102] in <d08fef6f170c48be9ae7bbe7c5d55a46>:0 
  at System.Diagnostics.Process.Start () [0x00032] in <d08fef6f170c48be9ae7bbe7c5d55a46>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in <d08fef6f170c48be9ae7bbe7c5d55a46>:0 
  at Eto.GtkSharp.Forms.ApplicationHandler.Open (System.String url) [0x00006] in <5c8e54e207324e56b9970aa5bec687f0>:0 
  at Eto.Forms.Application.Open (System.String url) [0x00006] in <b6695d6f4da049129c9b6c4a66d940de>:0 
```

## Code that Demonstrates the Problem
```c#
Application.Instance.Open("https://www.google.com");
```

## Specifications

  - Version: 2.5.1-ci-20200527.4 (latest ci build from yesterday)
  - Platform(s): Gtk
  - Operating System(s): Ubuntu 20.04, Mono 6.8 and 6.10 development build & other lower versions

**Comment by ManuelHu** [comment] 2020-05-28 09:11
For reference, this is the current code I'm using to fix this issue in my app: https://github.com/FPLedit/FPLedit/blob/develop/FPLedit.Shared/Helpers/OpenHelper.cs

Tested on Windows (UseShellExecute should not fail), and Linux.

**Comment by cwensley** [comment] 2020-05-28 16:30
Thanks @ManuelHu, this is a dupe of #1697. This is a bug with mono, not with Eto. I suppose we can add the workaround in Eto's code, but it really shouldn't be necessary.

As far as I know, .NET Core works with the recent update to set `UseShellExecute = true`.

**Comment by cwensley** [comment] 2020-05-28 17:21
That being said, a PR with the workaround would be welcome.  However, I'd do a try/catch around the _proper_ way to do it, then fallback to the workaround instead of the other way around.

**Comment by ManuelHu** [comment] 2020-05-28 20:02
I verified that it works on current core versions, and I will send a pull request for the workaround ;-)

**Closed as completed** 2020-05-28 20:33 UTC
