### ISSUE TITLE
Wpf -still crashes with DataGrid

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#1555] opened 2020-01-18 11:25 UTC
This crash happens irregular with some clients and is not reproducible.
There is some evidence, that it is in connection with update grid after changing/updating the datasource, maybe layout-cycle, because when its happen, the user did changes on the data, which is bound to the grid.
Since this is not reproducible, can you imagine of some place in code where the grid is refreshing where we could place a try-catch, so that we can at least avoid crashing the app?

```
QvxWin,  Version=1.0.3.30
64 bit, .NET Framework 4.8, Eto.Wpf.Platform
Copyright © 1996-2020 Thomas Flemming
 
Root folder qvx data:
D:\QuoVadis\QVX_Data
 
deviceid=5
cmdmanstatus=16 Tracks   (XplorerDetail)
 
date=18.01.2020 02:22:06
type=System.ArgumentNullException
message=Der Wert darf nicht NULL sein.
Parametername: key
stacktrace=   bei System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   bei System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   bei System.Windows.Controls.DataGridItemAttachedStorage.TryGetValue(Object item, DependencyProperty property, Object& value)
   bei System.Windows.Controls.DataGridRow.RestoreAttachedItemValue(DependencyObject objectWithProperty, DependencyProperty property)
   bei System.Windows.Controls.DataGridRow.SyncProperties(Boolean forcePrepareCells)
   bei System.Windows.Controls.DataGridRow.PrepareRow(Object item, DataGrid owningDataGrid)
   bei System.Windows.Controls.DataGrid.PrepareContainerForItemOverride(DependencyObject element, Object item)
   bei System.Windows.Controls.ItemsControl.MS.Internal.Controls.IGeneratorHost.PrepareItemContainer(DependencyObject container, Object item)
   bei System.Windows.Controls.VirtualizingStackPanel.InsertContainer(Int32 childIndex, UIElement container, Boolean isRecycled)
   bei System.Windows.Controls.VirtualizingStackPanel.AddContainerFromGenerator(Int32 childIndex, UIElement child, Boolean newlyRealized, Boolean isBeforeViewport)
   bei System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Double& computedUniformOrAverageContainerPixelSize, Boolean& computedAreContainersUniformlySized, Boolean& hasAnyContainerSpanChanged, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)
   bei System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   bei System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   bei System.Windows.Controls.Primitives.DataGridRowsPresenter.MeasureOverride(Size constraint)
   bei System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   bei System.Windows.UIElement.Measure(Size availableSize)
   bei System.Windows.ContextLayoutManager.UpdateLayout()
   bei System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by cwensley** [comment] 2020-01-22 05:09
Sorry @TomQv, still no idea what is going on with that given the stack trace.  perhaps you have a DataStore that is getting a null value inserted in some cases?

**Comment by TomQv** [comment] 2020-01-22 19:24
I know, my question was actually, if you can imagine a kind of error-handling inside eto to catch such exceptions?

**Comment by cwensley** [comment] 2020-02-20 22:55
Hey @TomQv probably your best bet is `DataGrid.PrepareContainerForItemOverride`. This will need you to create a custom handler for the GridView to use a custom subclass of WPF's DataGrid.  Or just use a modified Eto until you can get to the root of the problem..

**Comment by TomQv** [comment] 2020-02-21 08:16
How would DataGrid.PrepareContainerForItemOverride help?
I still cant reproduce the problem, but I believe, its in connection with async data-preparation.
We are using several grids in a complex ui presenting data from sqlite-dbs. Depending on user-interaction the data is prepared from sqlite in async-await tasks and then the grids are filled or updated. It might be possible, that there is clashing, but again, only randomly and rare.

**Comment by cwensley** [comment] 2020-06-15 08:52
@TomQv `PrepareContainerForItemOverride` would help as you can override that in the WPF class (it is in the stack trace you posted).  You need a custom handler to use a subclass of WPF's DataGrid, or override it in Eto's `Eto.Wpf.Forms.Controls.EtoDataGrid` to catch the exception and determine what in your application caused the exception to happen. 

I'm closing this issue as there's nothing I can do at this point to fix this.  However, if you do find the cause please feel free to reopen or create another issue with the details.

Thanks!

**Closed as completed by cwensley** 2020-06-15 08:52 UTC
Labels: needs repro
