### ISSUE TITLE
Exceptions in mac projects

### ISSUE THREAD

**Issue by observer1** [picoe/Eto#1064] opened 2018-03-22 03:11 UTC
Running this code generates an exception

new System.Data.DataSet().ReadXml("/Foo.xml");

System.Configuration.ConfigurationErrorsException: Error Initializing the configuration system.
innerexception: 
System.Configuration.ConfigurationErrorsException: Unrecognized configuration section <runtime>

Copying the section declaration from the machine.config file solves the issue, but then other codes fail, for example using a webrequest for http causes this:

The URI prefix is not recognized.

**Comment by cwensley** [comment] 2018-03-22 22:10
Thanks for reporting the issue, this is a dupe of #1049.

**Closed by cwensley** 2018-03-22 22:10 UTC
